/* Word Connect — category pool.
   Each set: a title and exactly 4 related words.
   Words are kept short-ish so four cards fit across a phone screen. */

const CATEGORIES = [
  { title: 'Days of the Week', words: ['MONDAY', 'TUESDAY', 'FRIDAY', 'SUNDAY'] },
  { title: 'Months of the Year', words: ['JANUARY', 'MARCH', 'JULY', 'OCTOBER'] },
  { title: 'Countries', words: ['BRAZIL', 'JAPAN', 'EGYPT', 'CANADA'] },
  { title: 'Capital Cities', words: ['PARIS', 'TOKYO', 'CAIRO', 'LIMA'] },
  { title: 'US States', words: ['TEXAS', 'ALASKA', 'NEVADA', 'OHIO'] },
  { title: 'Oceans & Seas', words: ['PACIFIC', 'ARCTIC', 'BALTIC', 'CORAL'] },
  { title: 'Farm Animals', words: ['COW', 'SHEEP', 'GOAT', 'PIG'] },
  { title: 'Big Cats', words: ['LION', 'TIGER', 'LEOPARD', 'CHEETAH'] },
  { title: 'Dogs', words: ['LABRADOR', 'HUSKY', 'PUG', 'CORGI'] },
  { title: 'Birds', words: ['EAGLE', 'FINCH', 'PENGUIN', 'OWL'] },
  { title: 'Sea Creatures', words: ['DOLPHIN', 'OCTOPUS', 'SHARK', 'CRAB'] },
  { title: 'Insects', words: ['BEETLE', 'WASP', 'MOTH', 'ANT'] },
  { title: 'Reptiles', words: ['GECKO', 'COBRA', 'TURTLE', 'IGUANA'] },
  { title: 'Vehicles', words: ['TRUCK', 'TRACTOR', 'SCOOTER', 'VAN'] },
  { title: 'Boats', words: ['CANOE', 'KAYAK', 'FERRY', 'YACHT'] },
  { title: 'Aircraft', words: ['JET', 'GLIDER', 'BALLOON', 'CHOPPER'] },
  { title: 'Shapes', words: ['CIRCLE', 'SQUARE', 'HEXAGON', 'OVAL'] },
  { title: 'Star Signs', words: ['LIBRA', 'ARIES', 'VIRGO', 'GEMINI'] },
  { title: 'Planets', words: ['MARS', 'VENUS', 'SATURN', 'NEPTUNE'] },
  { title: 'In the Night Sky', words: ['COMET', 'NEBULA', 'ECLIPSE', 'METEOR'] },
  { title: 'Colours', words: ['CRIMSON', 'INDIGO', 'AMBER', 'TEAL'] },
  { title: 'Fruits', words: ['BANANA', 'MANGO', 'CHERRY', 'PEACH'] },
  { title: 'Vegetables', words: ['CARROT', 'ONION', 'SPINACH', 'LEEK'] },
  { title: 'Nuts', words: ['ALMOND', 'CASHEW', 'WALNUT', 'PECAN'] },
  { title: 'Herbs & Spices', words: ['BASIL', 'THYME', 'CUMIN', 'SAGE'] },
  { title: 'Breakfast', words: ['CEREAL', 'TOAST', 'BACON', 'WAFFLE'] },
  { title: 'Fast Food', words: ['BURGER', 'FRIES', 'NUGGETS', 'TACO'] },
  { title: 'Desserts', words: ['SUNDAE', 'BROWNIE', 'TRIFLE', 'ECLAIR'] },
  { title: 'Drinks', words: ['COFFEE', 'COCOA', 'JUICE', 'SODA'] },
  { title: 'Cheeses', words: ['CHEDDAR', 'BRIE', 'FETA', 'GOUDA'] },
  { title: 'Pasta', words: ['PENNE', 'FUSILLI', 'RAVIOLI', 'LASAGNE'] },
  { title: 'Boxing', words: ['PUNCH', 'UPPERCUT', 'HOOK', 'JAB'] },
  { title: 'Team Sports', words: ['SOCCER', 'RUGBY', 'HOCKEY', 'CRICKET'] },
  { title: 'Athletics', words: ['JAVELIN', 'HURDLES', 'DISCUS', 'RELAY'] },
  { title: 'Tennis', words: ['SERVE', 'VOLLEY', 'DEUCE', 'LOB'] },
  { title: 'Golf', words: ['BIRDIE', 'BUNKER', 'PUTTER', 'CADDIE'] },
  { title: 'Chess Pieces', words: ['KING', 'ROOK', 'BISHOP', 'PAWN'] },
  { title: 'Card Games', words: ['POKER', 'RUMMY', 'BRIDGE', 'CANASTA'] },
  { title: 'Retro Games', words: ['TETRIS', 'PACMAN', 'ASTEROID', 'MARIO'] },
  { title: 'Instruments', words: ['VIOLIN', 'TRUMPET', 'PIANO', 'HARP'] },
  { title: 'Music Genres', words: ['JAZZ', 'REGGAE', 'TECHNO', 'BLUES'] },
  { title: 'Dances', words: ['TANGO', 'SALSA', 'WALTZ', 'SAMBA'] },
  { title: 'Film Genres', words: ['HORROR', 'COMEDY', 'WESTERN', 'THRILLER'] },
  { title: 'Luxury Cars', words: ['AUDI', 'BMW', 'MERCEDES', 'FERRARI'] },
  { title: 'Weather', words: ['DRIZZLE', 'THUNDER', 'BLIZZARD', 'FOG'] },
  { title: 'Landforms', words: ['CANYON', 'PLATEAU', 'VALLEY', 'DUNE'] },
  { title: 'Trees', words: ['OAK', 'WILLOW', 'BIRCH', 'MAPLE'] },
  { title: 'Flowers', words: ['TULIP', 'DAISY', 'ORCHID', 'LILY'] },
  { title: 'Gemstones', words: ['RUBY', 'OPAL', 'JADE', 'TOPAZ'] },
  { title: 'Metals', words: ['COPPER', 'NICKEL', 'ZINC', 'BRONZE'] },
  { title: 'Tools', words: ['HAMMER', 'CHISEL', 'WRENCH', 'PLIERS'] },
  { title: 'Kitchen Kit', words: ['WHISK', 'LADLE', 'GRATER', 'SIEVE'] },
  { title: 'Furniture', words: ['SOFA', 'DRESSER', 'STOOL', 'WARDROBE'] },
  { title: 'Clothing', words: ['BLAZER', 'SCARF', 'HOODIE', 'JEANS'] },
  { title: 'Footwear', words: ['SANDAL', 'LOAFER', 'BOOT', 'SNEAKER'] },
  { title: 'Body Parts', words: ['ELBOW', 'ANKLE', 'SHOULDER', 'WRIST'] },
  { title: 'Jobs', words: ['PLUMBER', 'DENTIST', 'BAKER', 'PILOT'] },
  { title: 'School Subjects', words: ['BIOLOGY', 'HISTORY', 'ALGEBRA', 'PHYSICS'] },
  { title: 'Emotions', words: ['JOY', 'ANGER', 'PRIDE', 'FEAR'] },
  { title: 'Holidays', words: ['EASTER', 'HALLOWEEN', 'NEW YEAR', 'DIWALI'] },
  { title: 'Mythical Beasts', words: ['DRAGON', 'GRIFFIN', 'PHOENIX', 'KRAKEN'] },
  { title: 'Greek Gods', words: ['ZEUS', 'HERA', 'APOLLO', 'HADES'] },
  { title: 'Superheroes', words: ['BATMAN', 'THOR', 'HULK', 'FLASH'] },
  { title: 'Coding Languages', words: ['PYTHON', 'JAVA', 'RUBY', 'SWIFT'] },
  { title: 'Board Games', words: ['CLUEDO', 'RISK', 'MONOPOLY', 'JENGA'] },
  { title: 'Camping Gear', words: ['TENT', 'LANTERN', 'COMPASS', 'STOVE'] },
  { title: 'Bathroom', words: ['TOWEL', 'MIRROR', 'RAZOR', 'SPONGE'] },
  { title: 'Currencies', words: ['DOLLAR', 'POUND', 'EURO', 'YEN'] },
  { title: 'Languages', words: ['FRENCH', 'GERMAN', 'ARABIC', 'HINDI'] },
  { title: 'Circus', words: ['CLOWN', 'TRAPEZE', 'JUGGLER', 'BIG TOP'] }
];
